// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile():Promise<void>;

export function GetFiles():Promise<Array<main.Item>>;

export function RemoveFile(arg1:number):Promise<void>;

export function UpdateStatus():Promise<void>;
