// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile() {
  return window['go']['main']['App']['AddFile']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function UpdateStatus() {
  return window['go']['main']['App']['UpdateStatus']();
}
